<?php
/**
 * @var $this \MvcCore\View
 * @var $generalLog \App\Models\LogFile
 * @var $connection \App\Models\Connection
 * @var $queriesStream \MvcCore\Ext\Models\Db\Readers\Streams\Iterator
 * @var $query \App\Models\Query
 */
?>

<div class="content">

	<a class="back" href="<?=$backLink?>">Back to processes list</a>

	<h1><?=$heading?></h1>

	<a 
		href="javascript:void(0);" 
		onclick="mark(this);"
		data-mark="<?=$connection->GetMark() ? 1 : 0 ?>"
		data-url="<?=$url('Connections:Mark', ['id_connection' => $connection->Id])?>">
		<?=$connection->GetMark() ? 'unmark' : 'mark' ?>
	</a>

	<h2>Thread ID: <?=$connection->GetIdThread()?></h2>

	<textarea id="requests-copy2clipboard" class="requests-copy2clipboard"></textarea>

	<div class="requests">
		<a class="expand-collapse-control" href="javascript:void(0);" onclick="handleExpandOrCollapseQueries(this);">
			<span class="expand">Expand All</span>
			<span class="collase">Collapse All</span>
		</a><?php

			$queriesStream->rewind();
			while ($queriesStream->valid()):

				$execGroupQueries = [];
				$executedDateTimeLast = NULL;
				$executedTimeStampLast = NULL;
				do {
					$query = $queriesStream->current();
					$executedDateTime = $query->GetExecuted();
					$executedTimeStamp = $executedDateTime->getTimestamp();
					if (
						$executedTimeStampLast !== NULL && 
						$executedTimeStamp !== $executedTimeStampLast
					) break;

					$requestNum = $query->GetRequestNumber();
					if (!isset($execGroupQueries[$requestNum]))
						$execGroupQueries[$requestNum] = [];
					$execGroupQueries[$requestNum][] = $query;

					$executedDateTimeLast = $executedDateTime;
					$executedTimeStampLast = $executedTimeStamp;

					$queriesStream->next();
				} while ($queriesStream->valid());

				$dateTime = $this->FormatDate($executedDateTimeLast);

			?><div class="request">
				<a class="expand-collapse-control" href="javascript:void(0);" onclick="handleExpandOrCollapseQueries(this);">
					<span class="expand">Expand All</span>
					<span class="collase">Collapse All</span>
				</a>
				<div class="date"><?=$dateTime?></div>
				<div class="request-content"><?php
				
				foreach ($execGroupQueries as $requestNum => $queryCommands): 
					
					$groupedCommands = [];
					$queryTypes = [];
					foreach ($queryCommands as $query) {
						$groupedCommands[] = $query->GetQueryTextCompressed();
						$queryTypes[] = 'query-type-' . $query->GetQueryTypeName();
					}
					$groupedCommand = implode(' ', $groupedCommands);
					$groupedCommand = $this->Truncate($groupedCommand, 180);
					
					$queryCommandsCount = count($queryCommands);
					$firstQuery = $queryCommands[0];
					$lastQuery = $queryCommands[$queryCommandsCount - 1];

					?><div class="request-queries <?php echo implode(" ", $queryTypes); ?>">
						<div class="request-queries-head">
							<span class="request-queries-head-count"><?=$queryCommandsCount?></span>
							<span class="request-queries-head-datetime"><?=$dateTime?></span>
							<span class="request-queries-head-id"><?=$requestNum?></span>
							<span class="request-queries-head-text"><?=$groupedCommand?></span>
						</div>
						<div class="request-queries-content hidden">
							<a class="request-queries-source" href="javascript:void(0);" onclick="editor(this,'<?php
								$lineCaption = $firstQuery->GetSourceLineBegin() - 10 >= 0
									? $firstQuery->GetSourceLineBegin() - 10
									: $firstQuery->GetSourceLineBegin();
								echo $url(
									'Editor:Index', [
										'idGeneralLog'	=> $generalLog->GetIdGeneralLog(),
										'lineBegin'		=> $firstQuery->GetSourceLineBegin(),
										'lineEnd'		=> $lastQuery->GetSourceLineEnd(),
										'linesRange'	=> 1000,
									]
								) . '#line-' . $lineCaption;
							?>');" target="_blank">source</a>
								
							<a 
							   class="request-queries-copy" 
							   href="javascript:void(0);" 
							   onclick="copy(this,'queries-<?=$requestNum?>');">copy</a>
								
							<div class="request-id">id: <?=$requestNum?></div>
								
							<div class="request-queries-count">count: <?=$queryCommandsCount?></div>
								
							<div class="request-datetime"><?=$dateTime?></div>
								
							<div id="queries-<?=$requestNum?>">
								<?php foreach ($queryCommands as $commandNumber => $queryCommand): ?>
									<div class="query-command" id="query-<?=$queryCommand->GetIdQuery()?>"><?php
										echo $queryCommand->GetQueryTextFormatted();
									?></div>
								<?php endforeach; ?>
							</div>
							
						</div>
					</div>

				<?php endforeach; ?>

			</div>
		</div>
		
		<?php endwhile; ?>

	</div>

</div>