<?php
/**
 * @var $this \MvcCore\View
 * @var $generalLog \App\Models\LogFile
 * @var $connection \App\Models\Connection
 * @var $allQueries \App\Models\Query[][][]
 * @var $requestQueries \App\Models\Query[][]
 * @var $queryCommands \App\Models\Query[]
 * @var $queryCommand \App\Models\Query
 */
?>

<div class="content">

	<a class="back" href="<?=$backLink?>">Back to processes list</a>

	<h1><?=$heading?></h1>

	<a 
		href="javascript:void(0);" 
		onclick="mark(this);"
		data-mark="<?=$connection->GetMark() ? 1 : 0 ?>"
		data-url="<?=$url('Connections:Mark', ['id_connection' => $connection->Id])?>">
		<?=$connection->GetMark() ? 'unmark' : 'mark' ?>
	</a>

	<h2>Thread ID: <?=$connection->GetIdThread()?></h2>

	<textarea id="requests-copy2clipboard" class="requests-copy2clipboard"></textarea>

	<div class="requests">
		<a class="expand-collapse-control" href="javascript:void(0);" onclick="handleExpandOrCollapseQueries(this);">
			<span class="expand">Expand All</span>
			<span class="collase">Collapse All</span>
		</a>
		<?php foreach ($queries as $dateTime => $requestQueries): ?>
			<div class="request">
				<a class="expand-collapse-control" href="javascript:void(0);" onclick="handleExpandOrCollapseQueries(this);">
					<span class="expand">Expand All</span>
					<span class="collase">Collapse All</span>
				</a>
				<div class="date"><?=$dateTime?></div>
				<div class="request-queries">
					<?php foreach ($requestQueries as $requestNumber => $queryCommands): ?>
						<?php
							$groupedCommands = [];
							$queryTypes = [];
							foreach ($queryCommands as $commandNumber => $queryCommand) {
								$groupedCommands[] = $queryCommand->GetQueryTextCompressed();
								$queryTypes[] = 'query-type-' . $queryCommand->GetQueryTypeName();
							}
							$groupedCommand = implode(' ', $groupedCommands);
							$groupedCommand = $this->Truncate($groupedCommand, 180);
						?>
						<div class="query <?php echo implode(" ", $queryTypes); ?>">
							<div class="query-head">
								<span class="query-head-count"><?=count($queryCommands)?></span>
								<span class="query-head-datetime"><?=$dateTime?></span>
								<span class="query-head-id"><?=$queryCommand->GetIdQuery()?></span>
								<span class="query-head-text"><?=$groupedCommand?></span>
							</div>
							<div class="query-content hidden">
								<a class="query-line" href="javascript:void(0);" onclick="editor(this,'<?php
									$lineCaption = $queryCommand->GetSourceLineBegin() - 10 >= 0
										? $queryCommand->GetSourceLineBegin() - 10
										: $queryCommand->GetSourceLineBegin();
									echo $url(
										'Editor:Index', [
											'idGeneralLog'	=> $generalLog->GetIdGeneralLog(),
											'lineBegin'		=> $queryCommand->GetSourceLineBegin(),
											'lineEnd'		=> $queryCommand->GetSourceLineEnd(),
											'linesRange'	=> 1000,
										]
									) . '#line-' . $lineCaption;
								?>');" target="_blank">source</a>
								
								<a class="query-copy" href="javascript:void(0);" onclick="copy(this,'query-<?php
									echo $queryCommand->GetIdQuery();
								?>');">copy</a>
								
								<div class="query-id">id: <?php echo $queryCommand->GetIdQuery()?></div>
								
								<div class="query-count">count: <?=count($queryCommands)?></div>
								
								<div class="query-datetime"><?=$dateTime?></div>
								
								<?php foreach ($queryCommands as $commandNumber => $queryCommand): ?>
									<div class="query-command" id="query-<?=$queryCommand->GetIdQuery()?>"><?=$queryCommand->GetQueryTextFormatted()?></div>
								<?php endforeach; ?>

							</div>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		<?php endforeach; ?>
	</div>

</div>