<?php /** @var $this \MvcCore\View */ ?>
<?php /** @var $generalLog \App\Models\LogFile */ ?>
<?php /** @var $connections \App\Models\Connection[] */ ?>

<div class="content">

	<a class="back" href="<?=$backLink?>">Back to general logs list</a>

	<h1><?=$heading?></h1>

	<?php echo $this->RenderScript('./paging'); ?>
	<br />

	<table class="connections">
		<tbody>
			<tr>
				<?php foreach ($orderFields as $orderFieldDbKey => $orderFieldText): ?>
					<th><a<?php 
						 if ($orderFieldDbKey === $currentOrder) {
							$newDir = $currentDir == 'asc' ? 'desc' : 'asc';
							echo ' class="selected"';
						 } else {
							 $newDir = $currentDir;
						 }
					?> href="<?php
						echo $url('self', [
							'dir'	=> $newDir, 
							'order'	=> $orderFieldDbKey,
						]);
					?>"><?php
						 echo $orderFieldText;
					?></a></th>
				<?php endforeach; ?>
				<th>selects</th>
				<th>inserts</th>
				<th>updates</th>
				<th>deletes</th>
			</tr>
		</tbody>
		<tbody>
			<?php foreach ($connections as $connection): ?>
				<tr<?php if ($connection->GetMark()) echo ' class="marked"'; ?>>
					<td>
						<a href="<?=$url('Queries:Index', [
							'id_connection'		=> $connection->GetIdConnection(),
						])?>"><?=$connection->GetIdConnection()?></a>
					</td>
					<td><a 
						  href="javascript:void(0);" 
						  onclick="mark(this);"
						  data-mark="<?=$connection->GetMark() ? 1 : 0 ?>"
						  data-url="<?=$url(':Mark', [
							'id_connection'		=> $connection->GetIdConnection(),
						  ])?>"><?php
							echo $connection->GetMark() ? 'unmark' : 'mark';
						?></a>
					</td>
					<td><?=$connection->GetIdThread()?></td>
					<td><?=$this->FormatDate(
						$connection->GetConnected()
					)?></td>
					<td><?php
						if ($connection->GetDisconnected() !== NULL) {
							echo $this->FormatDate(
								$connection->GetDisconnected()
							);
						}
					?></td>
					<td><?=$connection->GetRequestsCount()?></td>
					<td><?=$connection->GetQueriesCount()?></td>
					<td><?=$connection->GetUser()?></td>
					<td><?=$connection->GetDatabase()?></td>
					<td><?=$connection->GetSelectsCount()?></td>
					<td><?=$connection->GetInsertsCount()?></td>
					<td><?=$connection->GetUpdatesCount()?></td>
					<td><?=$connection->GetDeletesCount()?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	
	<br />
	<?php echo $this->RenderScript('./paging'); ?>

</div>